#!/usr/bin/env python3
"""Run a Case from a YAML config, or play it in 3D in Viser."""

from __future__ import annotations

import argparse
import json
import os
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from fourdirector import paths  # noqa: E402
from fourdirector.cases.receipts import forbid_repo_output  # noqa: E402
from fourdirector.cases.schema import load_case_yaml  # noqa: E402
from fourdirector.cases.stages import (  # noqa: E402
    OUTPUT_DIR,
    run_all,
    stage1_scene,
    stage2_objects,
    stage3_control,
    stage4_infer,
)


def default_run_root(case_id: str) -> Path:
    """Every generated byte lands under this checkout's ./output, which Git ignores."""
    return ROOT / OUTPUT_DIR / case_id


def resolve_viewer_root(config_path: Path, run_root: Path) -> Path:
    if (run_root / "case.json").is_file():
        return run_root
    raise SystemExit(
        f"nothing to view yet under {run_root}. Run stages 1 and 2 first: "
        f"python run.py stage1 --config {config_path} && "
        f"python run.py stage2 --config {config_path}"
    )


def launch_viser(
    config_path: Path,
    run_root: Path,
    *,
    host: str,
    port: int,
) -> None:
    import viser

    from fourdirector.examples.trajectory_viewer import configure_trajectory_viewer

    config = load_case_yaml(config_path)
    case_root = resolve_viewer_root(config_path, run_root)
    case = json.loads((case_root / "case.json").read_text(encoding="utf-8"))
    server = viser.ViserServer(host=host, port=port)
    configure_trajectory_viewer(
        server,
        case_root=case_root,
        case=case,
        namespace=config["case_id"],
    )
    print(f"Playing {config['case_id']} in Viser: http://{host}:{port}")
    print("Ctrl+C to stop.")
    try:
        while True:
            time.sleep(1.0)
    except KeyboardInterrupt:
        server.stop()


def main(argv: list[str] | None = None) -> int:
    # Paths that live elsewhere come from the same untracked components.env the
    # app reads, never from shell exports. Downloads stay in this checkout.
    paths.load_component_environment(ROOT)
    paths.use_checkout_caches()
    parser = argparse.ArgumentParser(
        description="Run a 4Director Case from a YAML config."
    )
    parser.add_argument(
        "command",
        nargs="?",
        default="all",
        choices=("all", "stage1", "stage2", "stage3", "stage4", "viser"),
        help="all runs stages 1–4. viser plays the Case's point cloud, objects and camera in 3D.",
    )
    parser.add_argument(
        "--config",
        type=Path,
        required=True,
        help="Case YAML, e.g. configs/cases/joint-camera.yaml",
    )
    parser.add_argument("--run-root", type=Path)
    parser.add_argument("--force", action="store_true")
    parser.add_argument(
        "--stub",
        action="store_true",
        help=argparse.SUPPRESS,
    )
    parser.add_argument("--host", default="localhost")
    parser.add_argument("--port", type=int, default=8080)
    checkpoint = os.environ.get("FOURDIRECTOR_CHECKPOINT")
    parser.add_argument(
        "--checkpoint",
        type=Path,
        default=Path(checkpoint).expanduser() if checkpoint else paths.MOTION_ADAPTER_CHECKPOINT,
        help="Motion Adapter weights for stage 4 (default: FOURDIRECTOR_CHECKPOINT in "
        "components.env, else models/4Director/step-2610.safetensors).",
    )
    parser.add_argument(
        "--seed",
        type=int,
        help="stage4 and all: sample with this seed instead of the Case's inference_seed, "
        "and write output-seed<SEED>.mp4 so several seeds sit side by side.",
    )
    args = parser.parse_args(argv)
    config_path = args.config.expanduser().resolve()
    config = load_case_yaml(config_path)
    run_root = (args.run_root or default_run_root(config["case_id"])).expanduser().resolve()
    forbid_repo_output(run_root, ROOT)
    if args.command == "viser":
        launch_viser(
            config_path,
            run_root,
            host=args.host,
            port=args.port,
        )
        return 0
    common = {
        "research_root": ROOT,
        "force": args.force,
        "stub": args.stub,
    }
    if args.command == "stage1":
        result = stage1_scene(config_path, run_root, **common)
    elif args.command == "stage2":
        result = stage2_objects(config_path, run_root, **common)
    elif args.command == "stage3":
        result = stage3_control(config_path, run_root, **common)
    elif args.command == "stage4":
        result = stage4_infer(
            config_path, run_root, checkpoint=args.checkpoint, seed=args.seed, **common
        )
    else:
        result = run_all(
            config_path,
            run_root,
            checkpoint=args.checkpoint,
            seed=args.seed,
            **common,
        )
    print(json.dumps(result, indent=2, sort_keys=True, default=str))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
