"""Four Case stages: scene, objects, control, inference."""

from __future__ import annotations

import csv
import hashlib
import json
import shutil
import subprocess
import sys
from collections.abc import Callable
from pathlib import Path
from typing import Any

import numpy as np
from PIL import Image

from fourdirector import paths
from fourdirector.cases.control_video import decoded_gray_identity
from fourdirector.cases.crops import (
    ADAPTER,
    GENERATOR,
    alignment_command,
    correspondence_command,
    crop_fov_x,
    write_padded_rgba,
)
from fourdirector.cases.receipts import (
    commit_attempt,
    forbid_repo_output,
    load_receipt,
    sha256_file,
    should_skip,
    write_json,
)
from fourdirector.cases.schema import NEGATIVE_PROMPT, load_case_yaml
from fourdirector.cases.trajectories import load_camera_matrices, load_object_trajectory
from fourdirector.constants import (
    FPS,
    FRAME_COUNT,
    FRAME_HEIGHT,
    FRAME_WIDTH,
    FULL_VACE_SHA256,
)
from fourdirector.stages.production import create_video_megasam_provider
from fourdirector.stages.trajectory import static_trajectory

CommandFn = Callable[[list[str]], None]

# Every generated byte lands here. Git ignores it; data/ stays inputs only.
OUTPUT_DIR = "output"


def _file_identity(path: Path) -> dict[str, Any]:
    resolved = path.expanduser()
    if not resolved.is_absolute():
        found = shutil.which(str(resolved))
        resolved = Path(found) if found else resolved
    return {
        "path": str(resolved),
        "sha256": sha256_file(resolved) if resolved.is_file() else None,
    }


def _resize_rgb(image: Path, destination: Path) -> Path:
    pixels = Image.open(image).convert("RGB")
    if pixels.size != (FRAME_WIDTH, FRAME_HEIGHT):
        pixels = pixels.resize((FRAME_WIDTH, FRAME_HEIGHT), Image.Resampling.BICUBIC)
    destination.parent.mkdir(parents=True, exist_ok=True)
    pixels.save(destination)
    return destination


def _resize_mask(mask: Path, destination: Path) -> Path:
    pixels = Image.open(mask).convert("L").resize(
        (FRAME_WIDTH, FRAME_HEIGHT), Image.Resampling.NEAREST
    )
    destination.parent.mkdir(parents=True, exist_ok=True)
    pixels.save(destination)
    return destination


def _resolve(path: str | Path, base: Path) -> Path:
    value = Path(path).expanduser()
    return value if value.is_absolute() else (base / value).resolve()


# Only stage 4 reads these; hashes are checks, not inputs. Leaving them out of
# the identity of stages 1-3 lets a new prompt or inference_seed rerun stage 4
# alone instead of the scene, the meshes, and the control.
STAGE4_ONLY_KEYS = ("prompt", "inference_seed", "hashes")


def _scene_config_sha256(config: dict[str, Any]) -> str:
    """Hash the Case YAML as stages 1-3 read it."""
    kept = {key: value for key, value in config.items() if key not in STAGE4_ONLY_KEYS}
    return hashlib.sha256(json.dumps(kept, sort_keys=True, default=str).encode()).hexdigest()


def _named_file_sha256(spec: Any, base: Path) -> str | None:
    """Hash the .npz a camera or trajectory names by path, so editing it reruns."""
    if isinstance(spec, dict) and spec.get("path"):
        return sha256_file(_resolve(spec["path"], base))
    return None


def _fit_mask(mask: Path, destination: Path, size: tuple[int, int]) -> Path:
    """Project one reconstruction mask onto the normalized scene image.

    Demo reconstruction inputs preserve the original 854x480 frame while the
    Case image is its 832x480 center crop.  Prefer that lossless crop over a
    geometric resize; other size changes use nearest-neighbour resampling.
    """
    pixels = Image.open(mask).convert("L")
    width, height = pixels.size
    target_width, target_height = size
    if height == target_height and width >= target_width:
        left = (width - target_width) // 2
        pixels = pixels.crop((left, 0, left + target_width, target_height))
    elif pixels.size != size:
        pixels = pixels.resize(size, Image.Resampling.NEAREST)
    destination.parent.mkdir(parents=True, exist_ok=True)
    pixels.save(destination)
    return destination


def _run(command: list[str], *, cwd: Path | None = None) -> None:
    subprocess.run(command, cwd=cwd, check=True)


def _background_from_geometry(
    geometry: Path,
    image: Path,
    scene_masks: list[Path],
    output: Path,
) -> tuple[np.ndarray, dict[str, Any]]:
    with np.load(geometry, allow_pickle=False) as archive:
        key = "depths" if "depths" in archive.files else "camera_z"
        depth = np.asarray(archive[key], dtype=np.float32)[0]
        intrinsics = np.asarray(archive["intrinsics"], dtype=np.float32)[0]
        w2c = np.asarray(archive["w2c"], dtype=np.float32)[0]
    rgb = np.asarray(Image.open(image).convert("RGB"))
    if depth.shape != rgb.shape[:2]:
        raise ValueError(f"stage1 geometry/image mismatch: {depth.shape} vs {rgb.shape}")
    removed = np.zeros(depth.shape, dtype=bool)
    for path in scene_masks:
        removed |= np.asarray(Image.open(path).convert("L")) > 0
    valid = np.isfinite(depth) & (depth > 0) & ~removed
    yy, xx = np.mgrid[: depth.shape[0], : depth.shape[1]]
    camera = np.stack(
        [
            (xx - intrinsics[0, 2]) * depth / intrinsics[0, 0],
            (yy - intrinsics[1, 2]) * depth / intrinsics[1, 1],
            depth,
            np.ones_like(depth),
        ],
        axis=-1,
    )
    c2w = np.linalg.inv(w2c)
    world = (c2w @ camera.reshape(-1, 4).T).T[:, :3].reshape(*depth.shape, 3)
    world[~np.isfinite(world).all(axis=-1)] = np.nan
    output.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(
        output,
        points=world[valid].astype(np.float32),
        colors=rgb[valid].astype(np.uint8),
        world_points_from_depth=world.astype(np.float32),
        camera_z=depth[None],
        validity=valid[None],
        removed_union_mask=removed,
        intrinsics=intrinsics[None],
        w2c=w2c[None],
    )
    return intrinsics, {
        "provider": "megasam",
        "points": int(valid.sum()),
        "removed_pixels": int(removed.sum()),
        "geometry": str(geometry),
    }


def _real_scene(
    image: Path,
    masks: list[Path],
    output: Path,
) -> dict[str, Any]:
    frames = output.parent / ".megasam-frames"
    if frames.exists():
        shutil.rmtree(frames)
    frames.mkdir(parents=True)
    for index in range(FRAME_COUNT):
        shutil.copyfile(image, frames / f"{index:06d}.png")
    geometry = output.parent / "megasam.npz"
    provider = create_video_megasam_provider()
    manifest = provider.run(frames, geometry)
    _, background = _background_from_geometry(geometry, image, masks, output)
    background["megasam"] = manifest
    shutil.rmtree(frames)
    return background


def _stub_scene(image: Path, masks: list[Path], output: Path) -> dict[str, Any]:
    rgb = np.asarray(Image.open(image).convert("RGB"))
    height, width = rgb.shape[:2]
    combined = np.zeros((height, width), dtype=bool)
    for mask_path in masks:
        combined |= np.asarray(Image.open(mask_path).convert("L")) > 0
    yy, xx = np.mgrid[0:height, 0:width]
    depth = np.full((height, width), 4.0, dtype=np.float32)
    fx = fy = 400.0
    cx, cy = width / 2.0, height / 2.0
    z = depth
    x = (xx - cx) * z / fx
    y = (yy - cy) * z / fy
    world = np.stack([x, y, z], axis=-1).astype(np.float32)
    keep = ~combined
    points = np.stack([x[keep], y[keep], z[keep]], axis=-1).astype(np.float32)
    colors = rgb[keep]
    output.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(
        output,
        points=points.reshape(-1, 3),
        colors=colors.reshape(-1, 3),
        world_points_from_depth=world,
        inverse_depth=(1.0 / np.maximum(depth, 1e-4))[None],
        camera_z=depth[None],
        validity=(~combined)[None],
        intrinsics=np.asarray(
            [[fx, 0.0, cx], [0.0, fy, cy], [0.0, 0.0, 1.0]], dtype=np.float32
        )[None],
        w2c=np.eye(4, dtype=np.float32)[None],
    )
    return {"provider": "cpu-stub", "points": int(keep.sum())}


def _write_camera(
    path: Path,
    extrinsics: np.ndarray,
    image: Path,
    intrinsics: np.ndarray | None = None,
) -> None:
    width, height = Image.open(image).size
    k = (
        np.asarray(intrinsics, dtype=np.float32)
        if intrinsics is not None
        else np.asarray(
            [[400.0, 0.0, width / 2.0], [0.0, 400.0, height / 2.0], [0.0, 0.0, 1.0]],
            dtype=np.float32,
        )
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(
        path,
        intrinsics=np.repeat(k[None, ...], FRAME_COUNT, axis=0),
        extrinsics=extrinsics.astype(np.float32),
        w2c=extrinsics.astype(np.float32),
        # The frozen renderer reads this field as [height, width].
        image_size=np.asarray([height, width], dtype=np.int32),
    )


def stage1_scene(
    config_path: Path,
    run_root: Path,
    *,
    research_root: Path,
    force: bool = False,
    stub: bool = False,
    scene_fn: Callable[..., dict[str, Any]] | None = None,
) -> dict[str, Any]:
    forbid_repo_output(run_root, research_root)
    config = load_case_yaml(config_path)
    # A Case may ship its scene point cloud; stage 1 then skips MegaSAM.
    scene_source = (
        _resolve(config["background"], config_path.parent)
        if config.get("background")
        else None
    )
    image = Path(config["image"]).expanduser()
    if not image.is_absolute():
        image = (config_path.parent / image).resolve()
    normalized = run_root / "inputs" / "image.png"
    _resize_rgb(image, normalized)
    mask_paths = []
    scene_mask_paths = []
    for spec in config["objects"]:
        name = str(spec["id"])
        source_image = _resolve(spec.get("image", config["image"]), config_path.parent)
        source_mask = _resolve(spec["mask"], config_path.parent)
        object_root = run_root / "inputs" / "objects" / name
        object_root.mkdir(parents=True, exist_ok=True)
        object_image = object_root / "image.png"
        object_mask = object_root / "mask.png"
        Image.open(source_image).convert("RGB").save(object_image)
        Image.open(source_mask).convert("L").save(object_mask)
        if Image.open(object_image).size != Image.open(object_mask).size:
            raise ValueError(f"{name} reconstruction image and mask have different sizes")
        mask_paths.append(object_mask)
        if bool(spec.get("in_scene", "image" not in spec)):
            scene_mask_paths.append(
                _fit_mask(
                    object_mask,
                    run_root / "inputs" / "scene-masks" / f"{name}.png",
                    (FRAME_WIDTH, FRAME_HEIGHT),
                )
            )
    identity = {
        "stage": "stage1",
        "config_sha256": _scene_config_sha256(config),
        "camera_sha256": _named_file_sha256(config["camera"], config_path.parent),
        "image_sha256": sha256_file(normalized),
        "mask_sha256": [sha256_file(path) for path in mask_paths],
        "scene_mask_sha256": [sha256_file(path) for path in scene_mask_paths],
        "megasam": "configured-upstream-entrypoints"
        if not stub and scene_source is None
        else None,
        "background_sha256": sha256_file(scene_source) if scene_source else None,
    }
    skipped = should_skip(run_root, "stage1", identity, force=force)
    if skipped is not None:
        skipped = dict(skipped)
        skipped["skipped"] = True
        return skipped
    expected = config.get("hashes", {}).get("image")
    if expected and sha256_file(image) != expected:
        raise ValueError("input image does not match hashes.image in the Case config")
    background = run_root / "scene" / "background.npz"
    camera = run_root / "cameras" / "camera.npz"
    if scene_source is not None and scene_fn is None:
        background.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(scene_source, background)
        extra = {"provider": "case-background", "background_sha256": sha256_file(background)}
    else:
        runner = scene_fn or (_stub_scene if stub else _real_scene)
        extra = runner(normalized, scene_mask_paths, background)
    with np.load(background, allow_pickle=False) as archive:
        scene_intrinsics = np.asarray(archive["intrinsics"], dtype=np.float32)[0]
    _write_camera(
        camera,
        load_camera_matrices(config["camera"], config_path.parent),
        normalized,
        scene_intrinsics,
    )
    (run_root / "inputs" / "case.yaml").write_text(
        config_path.read_text(encoding="utf-8"), encoding="utf-8"
    )
    return commit_attempt(
        run_root,
        stage="stage1",
        identity=identity,
        outputs=[normalized, background, camera, *mask_paths, *scene_mask_paths],
        extra=extra,
        force=force,
    )


def _stub_object(
    *,
    image: Path,
    mask: Path,
    seed: int,
    object_dir: Path,
    python: Path,
    repository: Path,
    **_: Any,
) -> dict[str, Any]:
    crop = object_dir / "crop_rgba.png"
    bbox = write_padded_rgba(image, mask, crop)
    mesh = object_dir / "mesh.glb"
    correspondence = object_dir / "pixal_correspondence.npz"
    preprocessed = object_dir / "pixal_preprocessed.png"
    command = correspondence_command(
        python=python,
        repository=repository,
        image=crop,
        mesh=mesh,
        correspondence=correspondence,
        preprocessed=preprocessed,
        fov_x=crop_fov_x(bbox, 400.0),
        seed=seed,
    )
    if "generate_with_correspondence.py" not in " ".join(command):
        raise RuntimeError("object stage must call correspondence Pixal3D")
    if "inference.py" in command:
        raise RuntimeError("object stage must not use the no-correspondence inference.py path")
    mesh.write_bytes(b"glTF-stub")
    np.savez_compressed(correspondence, uv=np.zeros((8, 2), dtype=np.float32))
    preprocessed.write_bytes(crop.read_bytes())
    motion = object_dir / "motion.npz"
    np.savez_compressed(motion, world_transforms=static_trajectory())
    align = alignment_command(
        python=python,
        mesh=mesh,
        correspondence=correspondence,
        camera_contract=object_dir / "camera_contract.npz",
        target=object_dir / "fit_target.npz",
        motion=motion,
        output=object_dir / "alignment.npz",
        erosion_pixels=1,
    )
    np.savez_compressed(
        object_dir / "camera_contract.npz",
        crop_bbox_xyxy=np.asarray(list(bbox.values())[:4], dtype=np.float32),
    )
    np.savez_compressed(
        object_dir / "fit_target.npz",
        frame0_mask=np.asarray(Image.open(mask).convert("L")) > 0,
    )
    np.savez_compressed(
        object_dir / "alignment.npz",
        holdout_median_over_diameter=np.asarray(0.01),
    )
    return {
        "status": "reconstructed-stub",
        "seed": seed,
        "command": command,
        "alignment_command": align,
        "crop": str(crop),
        "mesh": str(mesh),
        "mesh_sha256": sha256_file(mesh),
    }


def _fit_world_to_object_image(
    world: np.ndarray,
    object_size: tuple[int, int],
) -> np.ndarray:
    """Map normalized scene geometry back to its reconstruction image canvas."""
    height, width = world.shape[:2]
    object_width, object_height = object_size
    if (object_width, object_height) == (width, height):
        return world
    if object_height == height and object_width >= width:
        left = (object_width - width) // 2
        expanded = np.full((object_height, object_width, 3), np.nan, dtype=np.float32)
        expanded[:, left : left + width] = world
        return expanded
    raise ValueError(
        "in-scene reconstruction image must equal the Case image or be its "
        f"horizontal parent crop; got {(object_width, object_height)} vs {(width, height)}"
    )


def _real_object(
    *,
    image: Path,
    mask: Path,
    seed: int,
    object_dir: Path,
    python: Path,
    repository: Path,
    trajectory: np.ndarray,
    in_scene: bool,
    run_root: Path,
    pixal_fov: float | None = None,
    pixal_low_vram: bool = False,
    pixal_decimation_target: int = 100000,
    pixal_texture_size: int = 1024,
) -> dict[str, Any]:
    crop = object_dir / "crop_rgba.png"
    bbox = write_padded_rgba(image, mask, crop)
    mesh = object_dir / "mesh.glb"
    correspondence = object_dir / "pixal_correspondence.npz"
    preprocessed = object_dir / "pixal_preprocessed.png"
    command = correspondence_command(
        python=python,
        repository=repository,
        image=crop,
        mesh=mesh,
        correspondence=correspondence,
        preprocessed=preprocessed,
        fov_x=(
            float(pixal_fov)
            if pixal_fov is not None
            else crop_fov_x(bbox, 400.0)
        ),
        seed=seed,
        decimation_target=pixal_decimation_target,
        texture_size=pixal_texture_size,
        low_vram=pixal_low_vram,
    )
    _run(command, cwd=repository)
    for required in (mesh, correspondence, preprocessed):
        if not required.is_file():
            raise RuntimeError(f"Pixal3D did not produce {required}")

    alignment = object_dir / "alignment.npz"
    alignment_commands: list[list[str]] = []
    if in_scene:
        with np.load(run_root / "scene" / "background.npz", allow_pickle=False) as archive:
            world = np.asarray(archive["world_points_from_depth"], dtype=np.float32)
        with np.load(run_root / "cameras" / "camera.npz", allow_pickle=False) as archive:
            extrinsic = np.asarray(archive["extrinsics"], dtype=np.float32)[0]
            intrinsics = np.asarray(archive["intrinsics"], dtype=np.float32)[0]
        world = _fit_world_to_object_image(world, Image.open(mask).size)
        frame0_mask = np.asarray(Image.open(mask).convert("L"), dtype=np.uint8)
        target = object_dir / "fit_target.npz"
        np.savez_compressed(
            target,
            world_points_from_depth=world,
            frame0_mask=frame0_mask,
            extrinsic=extrinsic,
        )
        camera_contract = object_dir / "camera_contract.npz"
        np.savez_compressed(
            camera_contract,
            intrinsics=intrinsics,
            crop_bbox_xyxy=np.asarray(
                [bbox["x0"], bbox["y0"], bbox["x1"], bbox["y1"]],
                dtype=np.float32,
            ),
        )
        relative = trajectory @ np.linalg.inv(trajectory[0])[None]
        motion = object_dir / "motion.npz"
        np.savez_compressed(
            motion,
            world_transforms=relative.astype(np.float32),
            pose_gate_passed=np.asarray(True),
        )
        failure: subprocess.CalledProcessError | None = None
        for erosion in (1, 4):
            candidate = object_dir / f"alignment_r{erosion}.npz"
            align = alignment_command(
                python=python,
                mesh=mesh,
                correspondence=correspondence,
                camera_contract=camera_contract,
                target=target,
                motion=motion,
                output=candidate,
                erosion_pixels=erosion,
            )
            alignment_commands.append(align)
            try:
                _run(align)
                shutil.copyfile(candidate, alignment)
                failure = None
                break
            except subprocess.CalledProcessError as error:
                failure = error
        if failure is not None:
            raise failure
    else:
        # Inserted objects already carry an authored world-space placement.
        np.savez_compressed(
            alignment,
            canonical_to_world=trajectory.astype(np.float32),
            reference_frame=np.asarray(0, dtype=np.int32),
            alignment_gate_passed=np.asarray(True),
            placement_source=np.asarray("authored_trajectory"),
        )
    return {
        "status": "reconstructed",
        "seed": seed,
        "command": command,
        "alignment_commands": alignment_commands,
        "crop": str(crop),
        "mesh": str(mesh),
        "mesh_sha256": sha256_file(mesh),
        "alignment": str(alignment),
        "in_scene": in_scene,
    }


def stage2_objects(
    config_path: Path,
    run_root: Path,
    *,
    research_root: Path,
    force: bool = False,
    stub: bool = False,
    reconstruct: Callable[..., dict[str, Any]] | None = None,
    pixal3d_python: Path | None = None,
    pixal3d_repository: Path | None = None,
) -> dict[str, Any]:
    forbid_repo_output(run_root, research_root)
    config = load_case_yaml(config_path)
    # An object that names its mesh is used as is; the rest go through Pixal3D.
    meshes = {
        str(spec["id"]): _resolve(spec["mesh"], config_path.parent)
        for spec in config["objects"]
        if spec.get("mesh")
    }
    reconstructs = len(meshes) < len(config["objects"])
    python = pixal3d_python or Path(sys.executable)
    repository = pixal3d_repository or research_root / "third_party" / "Pixal3D"
    identity = {
        "stage": "stage2",
        "config_sha256": _scene_config_sha256(config),
        "trajectories": {
            str(spec["id"]): _named_file_sha256(spec.get("trajectory"), config_path.parent)
            for spec in config["objects"]
        },
        "stage1": (run_root / "current/stage1/receipt.json").read_text(encoding="utf-8")
        if (run_root / "current/stage1/receipt.json").is_file()
        else None,
        "python": _file_identity(python) if reconstructs else None,
        "pixal3d_repository": str(repository.expanduser().resolve()) if reconstructs else None,
        "generator": _file_identity(GENERATOR) if reconstructs else None,
        "pixal3d_adapter": (
            [_file_identity(ADAPTER), _file_identity(paths.script("pixal3d_patch"))]
            if reconstructs
            else None
        ),
        "aligner": (
            _file_identity(paths.script("aligner", root=research_root))
            if reconstructs
            else None
        ),
        "meshes": {name: sha256_file(path) for name, path in meshes.items()},
    }
    skipped = should_skip(run_root, "stage2", identity, force=force)
    if skipped is not None:
        skipped = dict(skipped)
        skipped["skipped"] = True
        return skipped
    if reconstructs and not stub and reconstruct is None:
        in_scene = [
            str(spec["id"])
            for spec in config["objects"]
            if not spec.get("mesh") and bool(spec.get("in_scene", "image" not in spec))
        ]
        with np.load(run_root / "scene" / "background.npz", allow_pickle=False) as archive:
            measured = "world_points_from_depth" in archive.files
        if in_scene and not measured:
            raise ValueError(
                f"{', '.join(in_scene)} must name a mesh: Pixal3D aligns an in-scene "
                "object to the depth MegaSAM measures, and this Case ships its "
                "background instead. Remove `background` as well to reconstruct both."
            )
    image = run_root / "inputs" / "image.png"
    reconstruct_fn = reconstruct or (_stub_object if stub else _real_object)
    outputs = []
    details = []
    stacked_masks = []
    for spec in config["objects"]:
        name = str(spec["id"])
        object_dir = run_root / "objects" / name
        object_dir.mkdir(parents=True, exist_ok=True)
        object_input = run_root / "inputs" / "objects" / name
        image = object_input / "image.png"
        mask = object_input / "mask.png"
        seed = int(spec.get("pixal_seed", 42))
        trajectory_path = object_dir / "trajectory.npz"
        trajectory_spec = spec.get("trajectory") or {
            "preset": spec.get("trajectory_preset", "identity")
        }
        if isinstance(trajectory_spec, str):
            trajectory_spec = {"preset": trajectory_spec}
        matrices = load_object_trajectory(trajectory_spec, config_path.parent)
        np.savez_compressed(trajectory_path, canonical_to_world=matrices)
        if name in meshes and reconstruct is None:
            # The trajectory of a shipped mesh already places it in the scene,
            # so it doubles as the alignment the renderer reads.
            mesh = object_dir / "mesh.glb"
            alignment = object_dir / "alignment.npz"
            shutil.copyfile(meshes[name], mesh)
            shutil.copyfile(trajectory_path, alignment)
            receipt = {
                "status": "case-mesh",
                "mesh": str(mesh),
                "mesh_sha256": sha256_file(mesh),
                "alignment": str(alignment),
                "alignment_sha256": sha256_file(alignment),
            }
            object_outputs = [mesh, trajectory_path, alignment]
        else:
            receipt = reconstruct_fn(
                image=image,
                mask=mask,
                seed=seed,
                object_dir=object_dir,
                python=python,
                repository=repository,
                trajectory=matrices,
                in_scene=bool(spec.get("in_scene", "image" not in spec)),
                run_root=run_root,
                pixal_fov=(
                    float(spec["pixal_fov"]) if "pixal_fov" in spec else None
                ),
                pixal_low_vram=bool(spec.get("pixal_low_vram", False)),
                pixal_decimation_target=int(
                    spec.get("pixal_decimation_target", 100000)
                ),
                pixal_texture_size=int(spec.get("pixal_texture_size", 1024)),
            )
            object_outputs = [
                object_dir / "mesh.glb",
                trajectory_path,
                object_dir / "alignment.npz",
                object_dir / "pixal_correspondence.npz",
                object_dir / "pixal_preprocessed.png",
            ]
        write_json(object_dir / "pixal3d.json", receipt)
        stacked_masks.append(np.asarray(Image.open(mask).convert("L")) > 0)
        outputs.extend([*object_outputs, object_dir / "pixal3d.json"])
        details.append(
            {
                "id": name,
                "mesh": f"objects/{name}/mesh.glb",
                "trajectory": f"objects/{name}/alignment.npz",
                "pixal3d_seed": None if name in meshes else seed,
                "receipt": f"objects/{name}/pixal3d.json",
            }
        )
    masks = np.stack(
        [np.repeat(mask[None, ...], FRAME_COUNT, axis=0) for mask in stacked_masks],
        axis=1,
    )
    mask_path = run_root / "object-masks.npz"
    np.savez_compressed(
        mask_path,
        masks_packed=np.packbits(masks, axis=-1),
        shape=np.asarray(masks.shape, dtype=np.int64),
        object_ids=np.asarray([spec["id"] for spec in config["objects"]]),
    )
    case = {
        "schema_version": "4director-user-case-v1",
        "case_id": config["case_id"],
        "objects": [spec["id"] for spec in config["objects"]],
        "objects_detail": details,
        "camera": "cameras/camera.npz",
        "reference_image": "inputs/image.png",
        "object_masks": "object-masks.npz",
        "prompt": config["prompt"],
        "negative_prompt": config.get("negative_prompt", NEGATIVE_PROMPT),
        "seed": int(config.get("inference_seed", 123)),
        "frame_count": FRAME_COUNT,
        "width": FRAME_WIDTH,
        "height": FRAME_HEIGHT,
        "fps": FPS,
        "num_inference_steps": 20,
        "cfg": 5,
        "sigma_shift": 5,
        "config": str(config_path),
    }
    case_json = run_root / "case.json"
    write_json(case_json, case)
    outputs.extend([mask_path, case_json])
    return commit_attempt(
        run_root,
        stage="stage2",
        identity=identity,
        outputs=outputs,
        extra={"stub": stub},
        force=force,
    )


def stage3_control(
    config_path: Path,
    run_root: Path,
    *,
    research_root: Path,
    force: bool = False,
    stub: bool = False,
    render_fn: Callable[..., dict[str, Any]] | None = None,
    renderer_python: Path | None = None,
) -> dict[str, Any]:
    forbid_repo_output(run_root, research_root)
    config = load_case_yaml(config_path)
    # VACE's reference image; the renderer writes the input image unless the
    # Case names another, like the teaser composite with the camel in place.
    reference = (
        _resolve(config["reference_image"], config_path.parent)
        if config.get("reference_image")
        else None
    )
    identity = {
        "stage": "stage3",
        "config_sha256": _scene_config_sha256(config),
        "stage2": sha256_file(run_root / "current/stage2/receipt.json")
        if (run_root / "current/stage2/receipt.json").is_file()
        else None,
        "renderer": _file_identity(paths.script("renderer", root=research_root))
        if not stub and render_fn is None
        else None,
        "renderer_python": _file_identity(renderer_python or Path(sys.executable)),
        "reference_image_sha256": sha256_file(reference) if reference else None,
    }
    skipped = should_skip(run_root, "stage3", identity, force=force)
    if skipped is not None:
        skipped = dict(skipped)
        skipped["skipped"] = True
        return skipped
    control_dir = run_root / "control"
    control_dir.mkdir(parents=True, exist_ok=True)
    control = control_dir / "vace_depth.mkv"
    if render_fn is not None:
        extra = render_fn(run_root=run_root, output=control)
    elif not stub:
        case = json.loads((run_root / "case.json").read_text(encoding="utf-8"))
        selected_ids = {str(value) for value in case["objects"]}
        source_stage = run_root / "renderer-input"
        rgb_dir = source_stage / "rgb"
        rgb_dir.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(run_root / "inputs" / "image.png", rgb_dir / "000000.png")
        command = [
            str(renderer_python or Path(sys.executable)),
            str(paths.script("renderer", root=research_root)),
        ]
        for detail in case["objects_detail"]:
            name = str(detail["id"])
            if name not in selected_ids:
                continue
            command.extend(["--mesh", str(run_root / detail["mesh"])])
            command.extend(["--transform", str(run_root / detail["trajectory"])])
            command.extend(["--object-id", name, "--reference-frame", "0"])
            source_mask = run_root / "inputs" / "objects" / name / "mask.png"
            runtime_mask = source_stage / "masks" / name / "000000.png"
            _fit_mask(source_mask, runtime_mask, (FRAME_WIDTH, FRAME_HEIGHT))
            for index in range(1, FRAME_COUNT):
                shutil.copyfile(
                    runtime_mask,
                    runtime_mask.with_name(f"{index:06d}.png"),
                )
        command.extend(
            [
                "--background",
                str(run_root / "scene" / "background.npz"),
                "--camera-depth",
                str(run_root / "cameras" / "camera.npz"),
                "--source-stage",
                str(source_stage),
                "--output-root",
                str(control_dir),
                "--width",
                str(FRAME_WIDTH),
                "--height",
                str(FRAME_HEIGHT),
                "--fps",
                str(FPS),
                "--batch-size",
                "9",
                "--point-size",
                "0.005",
                "--device",
                "cuda",
            ]
        )
        _run(command)
        if reference is not None:
            shutil.copyfile(reference, control_dir / "vace_reference_image.png")
        manifest_path = control_dir / "manifest.json"
        if not control.is_file() or not manifest_path.is_file():
            raise RuntimeError("production renderer did not produce its control bundle")
        decoded = decoded_gray_identity(control)
        expected = config.get("hashes", {}).get("control")
        if decoded is not None and expected and decoded["sha256"] != expected:
            print(
                f"note: {control} decodes to {decoded['sha256']}, not hashes.control "
                f"{expected}; a different GPU, driver, or package build can change it",
                file=sys.stderr,
            )
        extra = {
            "renderer": "production-shared-zbuffer",
            "command": command,
            "manifest": json.loads(manifest_path.read_text(encoding="utf-8")),
            "decoded_control": decoded,
            "expected_control": (
                {"expected": expected, "matches": decoded["sha256"] == expected}
                if decoded is not None and expected
                else None
            ),
            "historical_container_sha256": None,
        }
    else:
        control.write_bytes(b"FFV1-stub")
        extra = {"renderer": "cpu-stub"}
    sidecar = control_dir / "control.json"
    write_json(
        sidecar,
        {
            "schema_version": "4director-case-control-v1",
            "control": str(control),
            "control_sha256": sha256_file(control),
            "decoded_control": (
                extra.get("decoded_control")
                if isinstance(extra, dict)
                else None
            ),
            "frames": FRAME_COUNT,
            "width": FRAME_WIDTH,
            "height": FRAME_HEIGHT,
            "fps": FPS,
        },
    )
    outputs = [control, sidecar]
    if not stub and render_fn is None:
        outputs.extend(
            path
            for path in (
                control_dir / "vace_depth_preview.mp4",
                control_dir / "vace_depth_frame000.png",
                control_dir / "vace_video_mask.mkv",
                control_dir / "object_edit_mask.mkv",
                control_dir / "vace_reference_image.png",
                control_dir / "raw_sidecars.npz",
                control_dir / "depth_encoding.json",
                control_dir / "manifest.json",
            )
        )
    return commit_attempt(
        run_root,
        stage="stage3",
        identity=identity,
        outputs=outputs,
        extra=extra,
        force=force,
    )


def stage4_infer(
    config_path: Path,
    run_root: Path,
    *,
    research_root: Path,
    force: bool = False,
    stub: bool = False,
    infer_fn: Callable[..., dict[str, Any]] | None = None,
    checkpoint: Path | None = None,
    diffsynth_python: Path | None = None,
    seed: int | None = None,
) -> dict[str, Any]:
    forbid_repo_output(run_root, research_root)
    config = load_case_yaml(config_path)
    # A seed given here overrides the Case's inference_seed and names the video
    # after itself, so several seeds of one run sit side by side.
    seed_value = int(seed) if seed is not None else int(config.get("inference_seed", 123))
    checkpoint_sha256 = (
        sha256_file(checkpoint) if checkpoint is not None and checkpoint.is_file() else None
    )
    if checkpoint_sha256 is not None and checkpoint_sha256 != FULL_VACE_SHA256:
        print(
            f"note: {checkpoint} is not the released step-2610 Motion Adapter "
            f"(SHA-256 {FULL_VACE_SHA256})",
            file=sys.stderr,
        )
    identity = {
        "stage": "stage4",
        "config_sha256": sha256_file(config_path),
        "checkpoint": checkpoint_sha256 or ("stub" if stub else None),
        "stage3": sha256_file(run_root / "current/stage3/receipt.json")
        if (run_root / "current/stage3/receipt.json").is_file()
        else None,
        "runner": _file_identity(paths.script("vace_runner", root=research_root))
        if not stub and infer_fn is None
        else None,
        "diffsynth_python": _file_identity(diffsynth_python or Path(sys.executable)),
    }
    if seed is not None:
        identity["seed"] = seed_value
    skipped = should_skip(run_root, "stage4", identity, force=force)
    if skipped is not None:
        skipped = dict(skipped)
        skipped["skipped"] = True
        return skipped
    video = run_root / (f"output-seed{seed_value}.mp4" if seed is not None else "output.mp4")
    if infer_fn is not None:
        extra = infer_fn(run_root=run_root, output=video)
    elif not stub:
        if checkpoint is None or not checkpoint.is_file():
            raise FileNotFoundError(
                f"stage4 needs the Motion Adapter weights at {checkpoint}; run "
                "download_models.py, or pass --checkpoint / set FOURDIRECTOR_CHECKPOINT "
                "in components.env"
            )
        runner = paths.script("vace_runner", root=research_root)
        manifest = run_root / "inference" / "case.csv"
        manifest.parent.mkdir(parents=True, exist_ok=True)
        fields = [
            "case_id",
            "display_sequence",
            "dataset",
            "video",
            "vace_video",
            "vace_video_mask",
            "vace_reference_image",
            "input_manifest",
            "input_quality",
            "control_schema",
            "checkpoint_control_schema",
            "control_schema_compatible",
            "prompt",
            "seed",
            "control_frames",
            "model_frames",
            "output_frames",
        ]
        row = {
            "case_id": config["case_id"],
            "display_sequence": config["case_id"],
            "dataset": "4director-case",
            "video": str(run_root / "inputs" / "image.png"),
            "vace_video": str(run_root / "control" / "vace_depth.mkv"),
            # The teaser runs used the runner's implicit full-frame VACE
            # mask.  Stage 3 still emits the explicit all-white audit artifact.
            "vace_video_mask": "",
            "vace_reference_image": str(
                run_root / "control" / "vace_reference_image.png"
            ),
            "input_manifest": str(run_root / "control" / "manifest.json"),
            "input_quality": "complete",
            "control_schema": "4director-v7-control-v1",
            "checkpoint_control_schema": "4director-v7-control-v1",
            "control_schema_compatible": "true",
            "prompt": config["prompt"],
            # The only sampling seed after stage 2. A poor video can come from an
            # unlucky seed rather than a bad control: rerun stage 4 alone with
            # another --seed; stage 3 is seed-free.
            "seed": seed_value,
            "control_frames": FRAME_COUNT,
            "model_frames": FRAME_COUNT,
            "output_frames": FRAME_COUNT,
        }
        with manifest.open("w", newline="", encoding="utf-8") as handle:
            writer = csv.DictWriter(handle, fieldnames=fields)
            writer.writeheader()
            writer.writerow(row)
        generated_root = run_root / "inference" / "generated"
        command = [
            str(diffsynth_python or Path(sys.executable)),
            str(runner),
            "--manifest",
            str(manifest),
            "--output-root",
            str(generated_root),
            "--model",
            f"4Director={checkpoint}",
            "--height",
            str(FRAME_HEIGHT),
            "--width",
            str(FRAME_WIDTH),
            "--num-frames",
            str(FRAME_COUNT),
            "--fps",
            str(FPS),
            "--num-inference-steps",
            "20",
            "--rank",
            "0",
            "--world-size",
            "1",
            # This stage's receipt already decided to regenerate. The runner's
            # own resume check sees only the sampling settings, and would keep
            # a video made by another runner or cuDNN.
            "--force",
        ]
        _run(command)
        generated = generated_root / "4Director" / config["case_id"] / "generated.mp4"
        metadata = generated.with_name("run_metadata.json")
        if not generated.is_file() or not metadata.is_file():
            raise RuntimeError("Wan-VACE runner did not produce its output bundle")
        shutil.copyfile(generated, video)
        extra = {
            "adapter": "Full-VACE Motion Adapter, step 2610",
            "seed": seed_value,
            "command": command,
            "manifest": str(manifest),
            "metadata": json.loads(metadata.read_text(encoding="utf-8")),
        }
        # hashes.output is the video of the Case's own seed.
        own_seed = seed_value == int(config.get("inference_seed", 123))
        expected = config.get("hashes", {}).get("output") if own_seed else None
        stage3 = load_receipt(run_root / "current" / "stage3" / "receipt.json") or {}
        if expected and not (stage3.get("extra") or {}).get("edited"):
            produced = sha256_file(video)
            extra["expected_output"] = {"expected": expected, "matches": produced == expected}
            if produced != expected:
                print(
                    f"note: {video} differs from hashes.output {expected}; "
                    "a different GPU, driver, or package build can change the bytes",
                    file=sys.stderr,
                )
    else:
        video.write_bytes(b"H264-stub")
        extra = {
            "probe": {
                "frames": FRAME_COUNT,
                "width": FRAME_WIDTH,
                "height": FRAME_HEIGHT,
                "fps": FPS,
            },
            "adapter": "Full-VACE Motion Adapter, step 2610",
            "seed": seed_value,
        }
    return commit_attempt(
        run_root,
        stage="stage4",
        identity=identity,
        outputs=[
            video,
            *(
                [run_root / "inference" / "case.csv"]
                if not stub and infer_fn is None
                else []
            ),
        ],
        extra=extra,
        force=force,
    )


def run_all(
    config_path: Path,
    run_root: Path,
    *,
    research_root: Path,
    force: bool = False,
    stub: bool = False,
    pixal3d_python: Path | None = None,
    pixal3d_repository: Path | None = None,
    renderer_python: Path | None = None,
    diffsynth_python: Path | None = None,
    checkpoint: Path | None = None,
    seed: int | None = None,
) -> dict[str, Any]:
    common = {
        "research_root": research_root,
        "force": force,
        "stub": stub,
    }
    return {
        "stage1": stage1_scene(config_path, run_root, **common),
        "stage2": stage2_objects(
            config_path,
            run_root,
            pixal3d_python=pixal3d_python,
            pixal3d_repository=pixal3d_repository,
            **common,
        ),
        "stage3": stage3_control(
            config_path,
            run_root,
            renderer_python=renderer_python,
            **common,
        ),
        "stage4": stage4_infer(
            config_path,
            run_root,
            checkpoint=checkpoint,
            diffsynth_python=diffsynth_python,
            seed=seed,
            **common,
        ),
    }
